### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by TimWhiting** [isoos/buffer#5]
Null safety is now in [beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730). I would like to update my package to use null-safety, but I depend on this package.

Any ideas when you will upgrade? I'd be willing to submit a pull request. A quick check with `dart migrate` seems to provide a decent migration, but I understand if you would like to spend a bit more time and not have as many null asserts.

**Comment by isoos** [comment]
Hi! I appreciate and accept PRs :). Go ahead, I only ask you to be reasonable with asserts, it shouldn't have to impact the performance negatively...

**Comment by TimWhiting** [comment]
Can you publish a null-safe stable release now?

**Comment by isoos** [comment]
Done.
