### ISSUE TITLE
Reading zero bytes from end of buffer crashes.

### ISSUE THREAD

**Issue by adrianboyko** [isoos/buffer#7]
I encountered this minor problem in a project that reads a p-string (length prefixed) string at the end of a datagram. In one case, the length of the string was 0 and the subsequent read(0) crashed.

Here's a test case that simulates the situation I ran into. Think of [0,0,0,0] as a datagram that contains just one empty p-string.

``` dart
    test('Zero byte read at end of buffer', () {
      final buffer = [0,0,0,0]; 
      final reader = ByteDataReader();
      reader.add(buffer);
      final strLen = reader.readUint32();
      expect(strLen, equals(0));
      var noBytes = reader.read(strLen);
      expect(noBytes.length, equals(0));
    });
```
The work-around is to only call read(n) when n>0, but it would be better if read(0) just returned an empty Uint8List.

P.S. Thanks for publishing this library!

**Comment by isoos** [comment]
@adrianboyko: thanks for reporting! would you be interested filing a PR with a fix?
